//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATPHONG
    {
        public string IDDatPhong { get; set; }
        public string IDKhachHang { get; set; }
        public string IDPhong { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoNgayThucO { get; set; }
        public string UserID { get; set; }
        public string IDDichVu { get; set; }
        public string IDCoSo { get; set; }
        public string IDDonVi { get; set; }
    }
}
