//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNC
    {
        public string Func_code { get; set; }
        public int Sort { get; set; }
        public string Decription { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public string Parent { get; set; }
        public Nullable<bool> Menu { get; set; }
        public string Tips { get; set; }
    }
}
