//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public string IDPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string IDTang { get; set; }
        public string IDLoaiPhong { get; set; }
    }
}
